config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :products
  root 'static_pages#index'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_products
  has_many :products, through: :category_products
  has_many :sub_categories, class_name: "Category"
  belongs_to :parent_category, :class_name => "Category", :foreign_key => "parent_category_id"
  has_many :sub_categories, :class_name => "Category", :foreign_key => "parent_category_id"

  validates :title, uniqueness: true
end

app/models/category_product.rb
class CategoryProduct < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :category_products
  has_many :categories, through: :category_products

  mount_uploader :snap, SnapProductUploader

  class << self
    def filter_by_category category
      products = if category.present? && category.products.size > 0
                        category.products
                      else
                        Product.order("random()")
                      end
      if category == Category.first
        products.order("created_at desc").limit(Settings.product_limit.new)
      elsif category == Category.limit(2)[1]
        products.order("created_at desc").limit(Settings.product_limit.popular)
      end
    end

    def find_by_category category_title
      Category.find_by(title: category_title).products
    end
  end
end

app/models/trend.rb
class Trend < ApplicationRecord
  mount_uploader :snap, TrendUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # after_filter :allow_iframe
  before_action :set_locale

  def default_url_options options = {}
    {locale: I18n.locale}
  end

  private

  def allow_iframe
    response.headers.delete "X-Frame-Options"
  end

  def set_locale
    I18n.locale = params[:locale] || "vi"
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products  = if params[:category].present?
      Product.find_by_category(params[:category]).page(params[:page]).per(9)
    else
      Product.all.page(params[:page]).per(9)
    end
    @random_product = Product.all.sample
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :price, :size, :color, :description)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @new_arrivals = Product.filter_by_category(Category.first)
    @populer_product = Product.filter_by_category(Category.limit(2)[1])
    @categories = Category.where(parent_category: nil)
    @trends = Trend.all.limit(4)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def class_new_arrivals index
    default_class = 'col-md-3 new-grid simpleCart_shelfItem wow flipInY animated'

    class_name = if (index == 0 || index == 3)
                   default_class
                 elsif index == 1
                   "#{default_class} new-mdl"
                 else
                   class_name = "#{default_class} new-mdl1"
                 end
  end

  def class_popular_product index
    default_class = 'col-md-3 gallery-grid wow flipInY animated'

    class_name = if (index == 0 || index == 3)
                   default_class
                 elsif index == 1
                   "#{default_class} gallery-grid1"
                 else
                   class_name = "#{default_class} gallery-grid2"
                 end
  end
end

app/views/layouts/_header.html.erb
<div id="user_side_header">
  <a href="/" id="logo">
    <%= image_tag("logo.png") %>
  </a>
  <div id="banner_header">
    <%= image_tag("banner_b73dfe25.jpg", height: "87", width: "690") %>
  </div>
<!--   <div id="header_right">
      <div id="login_header">
              <i class="bg icon_user"></i><a href="http://www.hanoicomputer.vn/dang-ky" rel="nofollow">Đăng ký</a> | <a href="http://www.hanoicomputer.vn/dang-nhap" rel="nofollow">Đăng nhập</a>
      </div>
  </div> --><!--header_right-->
</div><!--header-->

app/views/products/_side_bar.html.erb
<div class="col-md-3 rsidebar">
  <div class="rsidebar-top">
    <div class="slider-left">
      <h4>Filter By Price</h4>
      <div id="slider-range"></div>
      <input type="text" id="amount" style="border: 0; color: #ffffff; font-weight: normal;"/>
      <!---->
      <script type='text/javascript'>//<![CDATA[
      $(window).load(function () {
        $("#slider-range").slider({
          range: true,
          min: 0,
          max: 9000,
          values: [1000, 7000],
          slide: function (event, ui) {
            $("#amount").val("$" + ui.values[0] + " - $" + ui.values[1]);
          }
        });
        $("#amount").val("$" + $("#slider-range").slider("values", 0) + " - $" + $("#slider-range").slider("values", 1));

      });//]]>
      </script>

      <!---->
    </div>
    <div class="sidebar-row">
      <h4> Clothes & Shoes </h4>
      <ul class="faq">
        <li class="item1"><a href="#">Frocks & Dresses<span class="glyphicon glyphicon-menu-down"></span></a>
          <ul>
            <li class=""><a href="#">Party Wear</a></li>
            <li class="subitem1"><a href="#">Night Wear</a></li>
            <li class="subitem1"><a href="#">Bath Time</a></li>
          </ul>
        </li>
        <li class="item2"><a href="#">Shorts & Jeans<span class="glyphicon glyphicon-menu-down"></span></a>
          <ul>
            <li class="subitem1"><a href="#">Girls</a></li>
            <li class="subitem1"><a href="#">Boys</a></li>
            <li class="subitem1"><a href="#">Baby by age</a></li>
          </ul>
        </li>
        <li class="item3"><a href="#">Protection <span class="glyphicon glyphicon-menu-down"></span></a>
          <ul>
            <li class="subitem1"><a href="#">Sweaters</a></li>
            <li class="subitem1"><a href="#">Rain Jackets</a></li>
            <li class="subitem1"><a href="#">Caps & Gloves</a></li>
          </ul>
        </li>
      </ul>
      <!-- script for tabs -->
      <script type="text/javascript">
        $(function () {

          var menu_ul = $('.faq > li > ul'),
              menu_a = $('.faq > li > a');

          menu_ul.hide();

          menu_a.click(function (e) {
            e.preventDefault();
            if (!$(this).hasClass('active')) {
              menu_a.removeClass('active');
              menu_ul.filter(':visible').slideUp('normal');
              $(this).addClass('active').next().stop(true, true).slideDown('normal');
            } else {
              $(this).removeClass('active');
              $(this).next().stop(true, true).slideUp('normal');
            }
          });

        });
      </script>
      <!-- script for tabs -->
    </div>
    <div class="sidebar-row">
      <h4>DISCOUNTS</h4>
      <div class="row row1 scroll-pane">
        <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Upto - 10% (20)</label>
        <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>70% - 60% (5)</label>
        <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>50% - 40% (7)</label>
        <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>30% - 20% (2)</label>
        <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>10% - 5% (5)</label>
        <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>30% - 20% (7)</label>
        <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>10% - 5% (2)</label>
        <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Other(50)</label>
      </div>
    </div>
  </div>
  <div class="gallery-grid ">
    <h6><%= t "products.also_like" %></h6>

    <%= link_to product_path(@random_product) do %>
      <%= image_tag @random_product.snap.also_like.url, class:"img-responsive", alt:"đồ chơi mua nhiều" %>
    <% end %>
    <div class="gallery-text simpleCart_shelfItem">
      <h5><%= link_to @random_product.title, product_path(@random_product), class: "name title_product" %></h5>
      <p><span class="item_price"><%= @random_product.price %></span></p>
      <h4 class="sizes">Sizes: <% @random_product.size.split(" ").each_with_index do |size, index| %>
          <a href=""><%= size %></a> <%= " - " if index != (@random_product.size.split(" ").size-1) %>
        <% end %>
      </h4>
    </div>
  </div>
</div>

app/views/products/edit.html.slim
h1 Editing product

== render 'form'

= link_to 'Show', @product
'|
= link_to 'Back', products_path

app/views/products/index.html.erb
<div class="breadcrumbs">
  <div class="container">
    <ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
      <li>
        <%= link_to root_path, class: "", data: { turbolinks: 'false' } do %>
          <i class="fa fa-home" aria-hidden="true"></i></span> <%= t "breadcrumbs.home" %>
        <% end %>
      </li>
      <li class="active"><%= t "breadcrumbs.product" %></li>
    </ol>
  </div>
</div>

<!--products-->
<div class="products">
  <div class="container">
    <div class="col-md-9 product-model-sec">
      <% @products.each_slice(3) do |three_product| %>
        <% three_product.each do |product| %>
          <% class_name = product == three_product[1] ? 'product-grids product-grids-mdl simpleCart_shelfItem wow fadeInUp animated' : 'product-grids simpleCart_shelfItem wow fadeInUp animated' %>
          <% wow_delay = 0.5 + (three_product.index(product))*0.2 %>

          <div class="<%= class_name %>" data-wow-delay=<%= wow_delay.to_s.concat("s") %> >
            <div class="new-top">
              <%= image_tag product.snap.item_index.url, class: "img-responsive", alt:"ôtô đồ chơi cho bé" %>
              <div class="new-text">
                <ul>
                  <li>
                    <%= link_to t("new_arrivals.quick_view"), product_path(product), class: "item_quantity" %>
                  </li>
                  <li><input type="number" class="item_quantity" min="1" value="1"></li>
                  <li><a class="item_add" href=""> <%= t("new_arrivals.add_cart") %></a></li>
                </ul>
              </div>
            </div>
            <div class="new-bottom">
              <h5>
                <%= link_to product.title, product_path(product), class: "name title_product", title:  product.title %>
              </h5>
              <div class="ofr">
                <p class="pric1">
                  <del><%= (product.price + (product.price)*0.2).round(2) %></del>
                </p>
                <p><span class="item_price"><%= product.price %></span></p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
      <%= paginate @products %>
    </div>

    <%= render "side_bar" %>
    <div class="clearfix"></div>
  </div>
</div>

app/views/products/new.html.slim
h1 New product

== render 'form'

= link_to 'Back', products_path

app/views/products/show.html.erb
<!--breadcrumbs-->
<div class="breadcrumbs">
  <div class="container">
    <ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
      <li class="">
        <%= link_to root_path, class: "", data: { turbolinks: 'false' } do %>
          <i class="fa fa-home" aria-hidden="true"></i></span> <%= t "breadcrumbs.home" %>
        <% end %>
      </li>
      <li class=""><%= link_to t("breadcrumbs.product"), products_path %></li>
      <li class="active"><%= t "breadcrumbs.details" %></li>
    </ol>
  </div>
</div>

<!--//breadcrumbs-->
<!--single-page-->
<div class="single">
  <div class="container">
    <div class="single-info">
      <div class="col-md-6 single-top wow fadeInLeft animated" data-wow-delay=".5s">
        <div class="flexslider">
          <div class="thumb-image">
            <%= image_tag @product.snap.url, "data-imagezoom": "true", class: "img-responsive", alt:""%>
          </div>
        </div>
      </div>
      <div class="col-md-6 single-top-left simpleCart_shelfItem wow fadeInRight animated" data-wow-delay=".5s">
        <h3><%= @product.title %></h3>
        <div class="single-rating">
          <span class="starRating">
            <input id="rating5" type="radio" name="rating" value="5" checked>
            <label for="rating5">5</label>
            <input id="rating4" type="radio" name="rating" value="4">
            <label for="rating4">4</label>
            <input id="rating3" type="radio" name="rating" value="3">
            <label for="rating3">3</label>
            <input id="rating2" type="radio" name="rating" value="2">
            <label for="rating2">2</label>
            <input id="rating1" type="radio" name="rating" value="1">
            <label for="rating1">1</label>
          </span>
          <!--<a href="#">Add Your Review</a>-->
        </div>
        <h6 class="item_price"><%= @product.price %></h6>
        <p><%= @product.summary %></p>
        <ul class="size">
          <h4><%= t "products.show.size" %></h4>
          <% @product.size.split(" ").each do |size| %>
            <li><a href="#"><%= size %></a></li>
          <% end %>
        </ul>
        <ul class="color">
          <h4><%= t "products.show.color" %></h4>
          <% @product.color.split.each do |color| %>
            <li><a href="#" style="background-color: <%= color %>; border: grey 1px solid"></a></li>
          <% end %>
        </ul>
        <div class="clearfix"> </div>
        <div class="quantity">
          <p class="qty"> <%= t "products.show.qty" %> :  </p><input min="1" type="number" value="1" class="item_quantity">
        </div>
        <div class="btn_form">
          <a href="#" class="add-cart item_add"><%= t "products.show.add_cart" %></a>
        </div>
      </div>
       <div class="clearfix"> </div>
    </div>
    <!--collapse-tabs-->
    <div class="collpse tabs">
      <div class="panel-group collpse" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default wow fadeInUp animated" data-wow-delay=".5s">
          <div class="panel-heading" role="tab" id="headingOne">
            <h4 class="panel-title">
              <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                <%= t "products.show.description" %>
              </a>
            </h4>
          </div>
          <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
            <div class="panel-body">
              <%= @product.description %>
            </div>
          </div>
        </div>
        <!--<div class="panel panel-default wow fadeInUp animated" data-wow-delay=".6s">-->
          <!--<div class="panel-heading" role="tab" id="headingTwo">-->
            <!--<h4 class="panel-title">-->
              <!--<a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">-->
                 <!--additional information-->
              <!--</a>-->
            <!--</h4>-->
          <!--</div>-->
          <!--<div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">-->
            <!--<div class="panel-body">-->
              <!--<%#= @product.description %>-->
            <!--</div>-->
          <!--</div>-->
        <!--</div>-->
        <!--<div class="panel panel-default wow fadeInUp animated" data-wow-delay=".7s">-->
          <!--<div class="panel-heading" role="tab" id="headingThree">-->
            <!--<h4 class="panel-title">-->
              <!--<a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">-->
                <!--reviews (5)-->
              <!--</a>-->
            <!--</h4>-->
          <!--</div>-->
          <!--<div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">-->
            <!--<div class="panel-body">-->
              <!--<%#= @product.description %>-->
            <!--</div>-->
          <!--</div>-->
        <!--</div>-->
        <!--<div class="panel panel-default wow fadeInUp animated" data-wow-delay=".8s">-->
          <!--<div class="panel-heading" role="tab" id="headingFour">-->
            <!--<h4 class="panel-title">-->
              <!--<a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">-->
                <!--help-->
              <!--</a>-->
            <!--</h4>-->
          <!--</div>-->
          <!--<div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">-->
            <!--<div class="panel-body">-->
              <!--<%#= @product.description %>-->
            <!--</div>-->
          <!--</div>-->
        <!--</div>-->
      </div>
    </div>
    <!--//collapse -->
    <!--related-products-->

    <!--//related-products-->
  </div>
</div>

  <script>
// Can also be used with $(document).ready()
$(window).load(function() {
  $('.flexslider').flexslider({
    animation: "slide",
    controlNav: "thumbnails"
  });
});
</script>
  <!--//search jQuery-->
  <!--smooth-scrolling-of-move-up-->
  <script type="text/javascript">
    $(document).ready(function() {

      var defaults = {
        containerID: 'toTop', // fading element id
        containerHoverID: 'toTopHover', // fading element hover id
        scrollSpeed: 1200,
        easingType: 'linear'
      };

      $().UItoTop({ easingType: 'easeOutQuart' });

    });
  </script>
  <!--//smooth-scrolling-of-move-up-->
  <!--Bootstrap core JavaScript
    ================================================== -->
    <!--Placed at the end of the document so the pages load faster -->

app/views/shared/_header.html.erb
<!--header-->
<div class="header">
  <!--<div class="top-header navbar navbar-default">&lt;!&ndash;header-one&ndash;&gt;-->
    <!--<div class="container">-->
      <!--<div class="nav navbar-nav wow fadeInLeft animated" data-wow-delay=".5s">-->
        <!--<p>Welcome to Modern Shoppe <a href="#">Register </a> Or <a href="#">Sign In </a></p>-->
      <!--</div>-->
      <!--<div class="nav navbar-nav navbar-right social-icons wow fadeInRight animated" data-wow-delay=".5s">-->
        <!--<ul>-->
          <!--<li><a href="#"> </a></li>-->
          <!--<li><a href="#" class="pin"> </a></li>-->
          <!--<li><a href="#" class="in"> </a></li>-->
          <!--<li><a href="#" class="be"> </a></li>-->
          <!--<li><a href="#" class="you"> </a></li>-->
          <!--<li><a href="#" class="vimeo"> </a></li>-->
        <!--</ul>-->
      <!--</div>-->
      <!--<div class="clearfix"></div>-->
    <!--</div>-->
  <!--</div>-->
  <div class="header-two navbar navbar-default"><!--header-two-->
    <div class="container">
      <div class="nav navbar-nav header-two-left">
        <ul>
          <li><i class="fa fa-phone" aria-hidden="true"></i> 0165 606 1585 </li>
          <li><i class="fa fa-envelope" aria-hidden="true"></i> <a href="mailto:info@example.com">hoangnhanc2@gmail.com</a>
          </li>
        </ul>
      </div>
      <div class="nav navbar-nav logo wow zoomIn animated" data-wow-delay=".7s">
        <h1>
          <%= link_to root_path, data: { turbolinks: 'false' } do %>
            <%= t "header.shop_name_first" %> <b><%= t "header.shop_name_last" %></b><span class="tag"><%= t "header.sub_shop_name" %> </span>
          <% end %>
        </h1>
      </div>
      <div class="nav navbar-nav navbar-right header-two-right">
        <div class="header-right my-account language">
          <%= link_to locale: "vi" do %>
            <%= image_tag "vi.png" %>
          <% end %>

          <span style="margin-left: 10px"></span>

          <%= link_to locale: "en" do %>
            <%= image_tag "en.png" %>
          <% end %>
        </div>
        <div class="header-right cart">
          <a href="#"><i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
          <h4><a href="#">
            <span class="simpleCart_total"> $0.00 </span>
            (<span id="simpleCart_quantity" class="simpleCart_quantity"> 0 </span>)
          </a></h4>
          <div class="cart-box">
            <p><a href="javascript:;" class="simpleCart_empty">Empty cart</a></p>
            <div class="clearfix"></div>
          </div>
        </div>
        <div class="clearfix"></div>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
  <div class="top-nav navbar navbar-default"><!--header-three-->
    <div class="container">
      <nav class="navbar" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <!--navbar-header-->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav top-nav-info">
            <li><%= link_to t("header.menu.home"), root_path, class: "#{'active' if params[:controller] == 'static_pages'}", data: { turbolinks: 'false' } %></li>
            <li><%= link_to t("header.menu.products"), products_path, class: "#{'active' if params[:controller] == 'products'}" %></li>

            <li class="dropdown grid">
              <a href="#" class="dropdown-toggle list1" data-toggle="dropdown"><%= t("header.menu.categories") %><b class="caret"></b></a>
              <ul class="dropdown-menu multi-column menu-two multi-column3">
                <div class="row">
                  <div class="col-sm-4 menu-grids">
                    <ul class="multi-column-dropdown">
                      <% Category.all.map(&:title).each do |category| %>
                        <li>
                          <%= link_to category, products_path(category: category), class: "list" %>
                        </li>
                      <% end %>
                    </ul>
                  </div>
                  <div class="col-sm-8 menu-grids">
                    <%= link_to products_path do %>
                      <div class="new-add">
                        <h5>30% OFF <br> <%= t("header.menu.today_only") %></h5>
                      </div>
                    <% end %>
                  </div>
                  <div class="clearfix"></div>
                </div>
              </ul>
            </li>

            <li><a href="codes.html"><%= t("header.menu.special_offers") %></a></li>
          </ul>
          <div class="clearfix"></div>
          <!--//navbar-collapse-->
          <!--<header class="cd-main-header">-->
            <!--<ul class="cd-header-buttons">-->
              <!--<li><a class="cd-search-trigger" href="#cd-search"> <span></span></a></li>-->
            <!--</ul> &lt;!&ndash; cd-header-buttons &ndash;&gt;-->
          <!--</header>-->
        </div>
        <!--//navbar-header-->
      </nav>
      <div id="cd-search" class="cd-search">
        <form>
          <input type="search" placeholder="Search...">
        </form>
      </div>
    </div>
  </div>
</div>
<!--//header-->

app/views/static_pages/_gallery.html.erb
<!--gallery-->
<div class="gallery">
  <div class="container">
    <div class="title-info wow fadeInUp animated" data-wow-delay=".5s">
      <h3 class="title"><%= t "gallery.first" %><span> <%= t "gallery.last" %></span></h3>
      <p><%= t "gallery.summary" %> </p>
    </div>
    <div class="gallery-info">
      <% @populer_product.each_slice(4) do |group| %>
        <% group.each_with_index do |product, index| %>
          <% wow_delay = 0.5 + (index)*0.2 %>
          <div class="<%= class_popular_product index %>" data-wow-delay=<%= wow_delay %>>
            <a href="products.html"><%=image_tag product.snap.item_index.url, class:"img-responsive", alt:"đồ chơi mua nhiều" %></a>
            <div class="gallery-text simpleCart_shelfItem">
              <h5><%= link_to product.title, product_path(product), class: "name title_product" %></h5>
              <p><span class="item_price"><%= product.price %></span></p>
              <h4 class="sizes">
                Sizes: <% product.size.split(" ").each_with_index do |size, index| %>
                  <a href=""><%= size %></a> <%= " - " if index != (product.size.split(" ").size-1) %>
                <% end %>
              </h4>
              <ul>
                <li><a href="#"><i class="fa fa-globe" aria-hidden="true"></i></a></li>
                <li><a class="item_add" href="#"><i class="fa fa-shopping-cart" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-heart" aria-hidden="true"></i></a></li>
              </ul>
            </div>
          </div>
        <% end %>
      <% end %>

      <div class="clearfix"></div>


    </div>
  </div>
</div>
<!--//gallery-->

app/views/static_pages/_new_ arrivals.html.erb
<!--new-->
<div class="new">
  <div class="container">
    <div class="title-info wow fadeInUp animated" data-wow-delay=".5s">
      <h3 class="title"><%= t("new_arrivals.first") %> <span><%= t("new_arrivals.last") %></span></h3>
      <p><%= t "new_arrivals.summary" %> </p>
    </div>

    <div class="new-info">
      <% @new_arrivals.each_with_index do |product, index| %>

        <% class_name = class_new_arrivals index%>

        <% wow_delay = 0.5 + (index)*0.2 %>
        <div class="<%= class_name %>" data-wow-delay=<%= wow_delay %> >
          <div class="new-top">
            <a href="#"><%= image_tag product.snap.new_arrivals.url, class:"img-responsive", alt:"đồ chơi mới về" %></a>
            <div class="new-text">
              <ul>
                <li><a class="item_add" href=""> <%= t "new_arrivals.add_cart" %></a></li>
                <li>
                  <%= link_to t("new_arrivals.quick_view"), product_path(product), class: "name" %>
                </li>
                <li>
                  <%= link_to t("new_arrivals.show_details"), product_path(product), class: "name" %>
                </li>
              </ul>
            </div>
          </div>
          <div class="new-bottom">
            <h5><%= link_to product.title, product_path(product), class: "name title_product" %></h5>
            <div class="ofr">
              <p class="pric1"><del><%= (product.price + (product.price)*0.2).round(2) %></del></p>
              <p><span class="item_price"><%= product.price %></span></p>
            </div>
          </div>
        </div>
      <% end %>
      <div class="clearfix"> </div>
    </div>
  </div>
</div>
<!--//new-->